import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";
import GlobalState from "@/context/Context";

export const metadata = {
  title: "Photo Plex App",
  description: "Generated by nextjs app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <Navbar />
          {children}
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
