import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Photo Plex App",
  description: "Generated by nextjs app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="   ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
